# Generated by Django 5.0.2 on 2024-03-17 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractRequestSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_request_id', models.PositiveIntegerField()),
                ('state', models.CharField(max_length=64)),
                ('state_start', models.DateTimeField()),
                ('state_end', models.DateTimeField()),
                ('comment', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonitoringContractRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('estimated_completion_date', models.DateField()),
                ('current_state_start', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('review', 'Review'), ('incomplete', 'Incomplete'), ('filed', 'Filed'), ('cancelled', 'Cancelled')], default='pending', max_length=64)),
                ('comment', models.TextField(blank=True, default='', null=True)),
                ('cenco', models.CharField(max_length=128)),
                ('has_money_in_cenco', models.BooleanField()),
                ('cenco_manager', models.CharField(max_length=256)),
                ('monitoring_type', models.CharField(choices=[('academic', 'Academic'), ('office', 'Office')], max_length=64)),
                ('student_code', models.CharField(max_length=16)),
                ('student_full_name', models.CharField(max_length=256)),
                ('student_id', models.CharField(max_length=16)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_cellphone', models.CharField(max_length=16)),
                ('daviplata', models.CharField(max_length=32)),
                ('course_or_proyect', models.CharField(max_length=256)),
                ('monitoring_description', models.TextField()),
                ('weekly_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('total_value_to_pay', models.DecimalField(decimal_places=2, max_digits=16)),
                ('is_unique_payment', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='customuser_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customuser_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CEXContractRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('estimated_completion_date', models.DateField()),
                ('current_state_start', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('review', 'Review'), ('incomplete', 'Incomplete'), ('filed', 'Filed'), ('cancelled', 'Cancelled')], default='pending', max_length=64)),
                ('comment', models.TextField(blank=True, default='', null=True)),
                ('solicitant_name', models.CharField(max_length=128)),
                ('solicitant_faculty', models.CharField(max_length=128)),
                ('hiree_full_name', models.CharField(max_length=256)),
                ('hiree_id', models.IntegerField()),
                ('hiree_cellphone', models.CharField(max_length=16)),
                ('hiree_email', models.EmailField(max_length=254)),
                ('cenco', models.CharField(max_length=128)),
                ('request_motive', models.TextField()),
                ('banking_entity', models.CharField(max_length=128)),
                ('bank_account_type', models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings')], max_length=64)),
                ('bank_account_number', models.CharField(max_length=32)),
                ('eps', models.CharField(max_length=64)),
                ('pension_fund', models.CharField(max_length=64)),
                ('arl', models.CharField(max_length=64, null=True)),
                ('contract_value', models.DecimalField(decimal_places=2, max_digits=16)),
                ('charge_account', models.TextField(null=True)),
                ('rut', models.FileField(upload_to='C:\\Users\\alejo\\OneDrive\\Escritorio\\hiring_project\\proyecto-t5\\hiring_module\\hiring_app\\media\\rut')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cex_contract_requests_assigned_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='contractrequestsnapshot',
            constraint=models.UniqueConstraint(fields=('contract_request_id', 'state'), name='unique_contract_request_snapshot'),
        ),
        migrations.AddField(
            model_name='monitoringcontractrequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_contract_requests_assigned_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
