# Generated by Django 5.0.2 on 2024-03-18 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cexcontractrequest',
            name='rut',
            field=models.FileField(upload_to='C:\\Users\\Juan Diaz\\OneDrive - Universidad Icesi\\Quinto semestre\\Proyecto integrador\\proyecto-t5\\hiring_module\\hiring_app\\media\\rut'),
        ),
    ]
