# Generated by Django 5.0.2 on 2024-03-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring_app', '0002_alter_cexcontractrequest_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cexcontractrequest',
            name='rut',
            field=models.FileField(upload_to='C:\\Users\\alejo\\OneDrive\\Escritorio\\hiring_project\\proyecto-t5\\hiring_module\\hiring_app\\media\\rut'),
        ),
    ]
