# Generated by Django 5.0.2 on 2024-03-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring_app', '0003_alter_cexcontractrequest_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cexcontractrequest',
            name='rut',
            field=models.FileField(upload_to='D:\\ver + local\\proyecto-t5\\hiring_module\\hiring_app\\media\\rut'),
        ),
    ]
